### ISSUE TITLE
Not able to use wordlists !

### ISSUE THREAD

**Issue by ivasugarg** [AlexisAhmed/BugBountyToolkit#27]
I am not able to use wordlists with tools such gobuster,dirb or any other tool which requires the use of it.
For instance when I tried trying to using it with dirb,it gets stuck at * Generating Wordlist...

dirb http://192.168.43.27 ~/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt 

-----------------
DIRB v2.22    
By The Dark Raver
-----------------

START_TIME: Sun Jul  5 13:22:52 2020
URL_BASE: http://192.168.43.27/
WORDLIST_FILES: /root/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt

-----------------

^C* Generating Wordlist...

**Comment by AlexisAhmed** [comment]
If you are using the Ubuntu/Debian install script, you will need to troubleshoot the issues manually. We have run various tests and the tools are all working. All wordlist based tools like Hydra, gobuster, dirb and wpscan are all working in the docker image. We have attached the images below. Additionally, make sure the wordlists are in the correct working directory when specifying them.
![dirb](https://user-images.githubusercontent.com/13276084/86539649-f2a79780-bf06-11ea-81df-1718ab7837a0.png)
![gobuster](https://user-images.githubusercontent.com/13276084/86539681-38646000-bf07-11ea-952b-fe07786c4c36.png)

**Comment by ivasugarg** [comment]
I am using the docker image.


Results for dirb remains the same as mentioned above.Since I am using docker you can verify the path for the wordlist which btw is correct afaik.

~ dirb http://192.168.43.27/ ~/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt 

-----------------
DIRB v2.22    
By The Dark Raver
-----------------

START_TIME: Sun Jul  5 15:20:23 2020
URL_BASE: http://192.168.43.27/
WORDLIST_FILES: /root/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt

-----------------

^C* Generating Wordlist...

&

~ dirb https://www.hackersploit.org/ ~/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt

-----------------
DIRB v2.22    
By The Dark Raver
-----------------

START_TIME: Sun Jul  5 15:25:26 2020
URL_BASE: https://www.hackersploit.org/
WORDLIST_FILES: /root/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt

-----------------

*** Generating Wordlist...


Why is this happening?Please help me out. 
I'm stuck.

**Comment by derfshaya** [comment]
I was having trouble with the same wordlist for dirb. This wordlist is particularly long, though I am not sure if that is the main reason. What I did was split this wordlist up using `split -l 10000 directory-list-2.3-medium.txt` and work through the 20+ split files one by one instead.

Some words were not generated in dirb though. Each file was 10000 lines long, but less than 10000 words were generated in a dirb execution using some files. I can identify them individually but it will be a long process.

**Comment by AlexisAhmed** [comment]
I am currently testing the issue and will respond with feedback and hopefully a fix.
