### ISSUE TITLE
Stuck at Generating Wordlists!

### ISSUE THREAD

**Issue by ivasugarg** [AlexisAhmed/BugBountyToolkit#28]
While using the docker image:

DIRB v2.22
By The Dark Raver
START_TIME: Sun Jul 5 15:25:26 2020
URL_BASE: https://www.hackersploit.org/
WORDLIST_FILES: /root/wordlists/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt

*** Generating Wordlist...

**Comment by AlexisAhmed** [comment]
Please ensure you have updated the image to the latest version, as mentioned previously, we have performed an in-depth and thorough test on multiple systems and VPS hosts and the wordlists are fully functional in conjunction with the relevant tools.

**Comment by ivasugarg** [comment]
Already updated:

Using default tag: latest
latest: Pulling from hackersploit/bugbountytoolkit
Digest: sha256:f348bf680198383857dc78a764bbd0a48e12ed222ac0e950d320a79147efecb7
Status: Image is up to date for hackersploit/bugbountytoolkit:latest
docker.io/hackersploit/bugbountytoolkit:latest

**Comment by derfshaya** [comment]
I was having trouble with the same wordlist for dirb. This wordlist is particularly long, though I am not sure if that is the main reason. What I did was split this wordlist up using `split -l 10000 directory-list-2.3-medium.txt` and work through the 20+ split files one by one instead.

Some words were not generated in dirb though. Each file was 10000 lines long, but less than 10000 words were generated in a dirb execution using some files. I can identify them individually but it will be a long process.
