### ISSUE TITLE
sudo up docker image Error'ed out with "libc-bin exit code 139"

### ISSUE THREAD

**Issue by gitezri** [AlexisAhmed/BugBountyToolkit#29]
Fetched 43.2 MB in 13s (3321 kB/s)                                                                                
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 28381 files and directories currently installed.)
Preparing to unpack .../libc6-dev_2.27-3ubuntu1.2_amd64.deb ...
Unpacking libc6-dev:amd64 (2.27-3ubuntu1.2) over (2.27-3ubuntu1) ...
Preparing to unpack .../libc-dev-bin_2.27-3ubuntu1.2_amd64.deb ...
Unpacking libc-dev-bin (2.27-3ubuntu1.2) over (2.27-3ubuntu1) ...
Preparing to unpack .../linux-libc-dev_4.15.0-111.112_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.15.0-111.112) over (4.15.0-106.107) ...
Preparing to unpack .../libc6_2.27-3ubuntu1.2_amd64.deb ...
Unpacking libc6:amd64 (2.27-3ubuntu1.2) over (2.27-3ubuntu1) ...
Setting up libc6:amd64 (2.27-3ubuntu1.2) ...
(Reading database ... 28381 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.27-3ubuntu1.2_amd64.deb ...
Unpacking libc-bin (2.27-3ubuntu1.2) over (2.27-3ubuntu1) ...
Setting up libc-bin (2.27-3ubuntu1.2) ...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@43e421ca836b:~/toolkit#

**Comment by AlexisAhmed** [comment]
Could you please elaborate on the issue a little further, for example; what are you trying to install?
