### ISSUE TITLE
New Tool Inclusion

### ISSUE THREAD

**Issue by Zinkuth** [AlexisAhmed/BugBountyToolkit#31]
I suggest you to add the tool 'httpx' from ProjectDiscovery.

Github url: https://github.com/projectdiscovery/httpx

**Comment by AlexisAhmed** [comment]
![Build log](https://user-images.githubusercontent.com/13276084/89675072-f78aad00-d8f1-11ea-9cab-8eb29dbebd51.png)
![Build failed](https://user-images.githubusercontent.com/13276084/89675075-f9547080-d8f1-11ea-85a7-41ff324aefa7.png)
