### ISSUE TITLE
Tools Suggestions Only: [not a issue]

### ISSUE THREAD

**Issue by b0ssh3r3** [AlexisAhmed/BugBountyToolkit#39]
Add more tools like:

gau
ffuf
john
hashcat
waybackurls
kxss
httprobe
httpx
gf
nuclei
dalfox
fping
metasploit
qsreplace
impacket
gitgrabber
xsshunter
gdb

**Comment by AlexisAhmed** [comment]
Thank you, we will work on adding them.
