### ISSUE TITLE
Add Tmux support

### ISSUE THREAD

**Issue by rishabhdeepsingh** [AlexisAhmed/BugBountyToolkit#5]
while running on nmap or something it takes time and we can use tmux to switch between the terminal easily.

**Comment by brutalgg** [comment]
Are you referring to tmux in the docker container?

**Comment by rishabhdeepsingh** [comment]
Yes, Exactly.

**Comment by rishabhdeepsingh** [comment]
If you want I can send a PR

**Comment by AlexisAhmed** [comment]
You can utilize the exec command to deploy more than one session for each container. This can be done by running the following command for every new session:
`docker exec -it <ID> /bin/bash`

> Note: Ensure that the container is running.

**Comment by rishabhdeepsingh** [comment]
I thought Tmux would be a better tool to work on as there is a lot quick switching etc.
